const dashboardData = {
    months: {
        4: {
            global: { baseDate: '2026-04-30', totalBusinessDays: 22, currentBusinessDay: 22, wirelessDays: 27, wiredDays: 23.1, elapsedDays: 27, wirelessProgress: 1.0, wiredProgress: 1.0, prevMonth: { achievedCount: 19, totalAmount: 140000000 } },
            agencies: [
                { id: 'D33654', name: '더블유', manager: '김기획', summary: { wirelessRate: 33.5, wiredRate: 30, retailArpuRate: 102.9, usimMnpRate: 38, totalAmount: 15000000, wirelessDetails: {target: 856, current: 286.4}, wiredDetails: {target: 463, current: 139.0}, retailDetails: {target: 80186, current: 82528}, mnpDetails: {target: 422, current: 160.5}, benefitHighUpgrade: 77, benefitHighMnp: 13, benefitGal26: 7 }, targetStatus: { goalScore: 90, currentScore: 33.5, bonusUsageRate: 79.5, aiSuggestion: "안정적인 실적" }, strengths: [{ name: "5G 전체", score: 119 }, { name: "전연령 010신규", score: 19 }], detailedItems: [{ name: "LTE 신규", multiplier: 1.0, performance: 15, score: 15 }, { name: "5G 전체", multiplier: 1.0, performance: 119, score: 119 }, { name: "전연령 010신규", multiplier: 1.0, performance: 19, score: 19 }] },
                { id: 'D33573', name: '솔로몬', manager: '김기획', summary: { wirelessRate: 32.1, wiredRate: 39.7, retailArpuRate: 98.1, usimMnpRate: 37.9, totalAmount: 3500000, wirelessDetails: {target: 587, current: 188.7}, wiredDetails: {target: 80, current: 31.7}, retailDetails: {target: 80186, current: 78634}, mnpDetails: {target: 33, current: 12.5}, benefitHighUpgrade: 57, benefitHighMnp: 10, benefitGal26: 11 }, targetStatus: { goalScore: 90, currentScore: 32.1, bonusUsageRate: 76.4, aiSuggestion: "상세 관리 필요" }, strengths: [{ name: "5G 전체", score: 112 }, { name: "010 USIM 개통", score: 7 }], detailedItems: [{ name: "LTE 신규", multiplier: 1.0, performance: 6, score: 6 }, { name: "5G 전체", multiplier: 1.0, performance: 112, score: 112 }, { name: "010 USIM 개통", multiplier: 1.0, performance: 7, score: 7 }] },
                { id: 'D33223', name: '남부', manager: '김기획', summary: { wirelessRate: 34.1, wiredRate: 20, retailArpuRate: 93, usimMnpRate: 28, totalAmount: 0, wirelessDetails: {target: 400, current: 136.4}, wiredDetails: {target: 120, current: 24}, retailDetails: {target: 80186, current: 75000}, mnpDetails: {target: 50, current: 14}, benefitHighUpgrade: 30, benefitHighMnp: 8, benefitGal26: 5 }, targetStatus: { goalScore: 90, currentScore: 34.1, bonusUsageRate: 65, aiSuggestion: "집중 관리 기간" }, strengths: [{ name: "5G 전체", score: 85 }, { name: "LTE 신규", score: 10 }], detailedItems: [{ name: "LTE 신규", multiplier: 1.0, performance: 10, score: 10 }, { name: "5G 전체", multiplier: 1.0, performance: 85, score: 85 }] },
                { id: 'D33434', name: '중앙SK', manager: '김기획', summary: { wirelessRate: 37.0, wiredRate: 36, retailArpuRate: 101, usimMnpRate: 35, totalAmount: 12000000, wirelessDetails: {target: 500, current: 185}, wiredDetails: {target: 250, current: 90}, retailDetails: {target: 80186, current: 81000}, mnpDetails: {target: 100, current: 25}, benefitHighUpgrade: 45, benefitHighMnp: 12, benefitGal26: 8 }, targetStatus: { goalScore: 90, currentScore: 37.0, bonusUsageRate: 81, aiSuggestion: "양호한 흐름" }, strengths: [{ name: "5G 전체", score: 120 }, { name: "전연령 010신규", score: 20 }], detailedItems: [{ name: "LTE 신규", multiplier: 1.0, performance: 15, score: 15 }, { name: "5G 전체", multiplier: 1.0, performance: 120, score: 120 }] },
                { id: 'D33732', name: '돌파', manager: '김기획', summary: { wirelessRate: 40.0, wiredRate: 33, retailArpuRate: 98, usimMnpRate: 45, totalAmount: 4500000, wirelessDetails: {target: 350, current: 140}, wiredDetails: {target: 150, current: 50}, retailDetails: {target: 80186, current: 79000}, mnpDetails: {target: 80, current: 30}, benefitHighUpgrade: 22, benefitHighMnp: 5, benefitGal26: 3 }, targetStatus: { goalScore: 90, currentScore: 40.0, bonusUsageRate: 88, aiSuggestion: "추가 달성 가능" }, strengths: [{ name: "5G 전체", score: 90 }, { name: "전연령 010신규", score: 25 }], detailedItems: [{ name: "LTE 신규", multiplier: 1.0, performance: 12, score: 12 }, { name: "5G 전체", multiplier: 1.0, performance: 90, score: 90 }] },
                { id: 'D33281', name: '문경새재', manager: '김기획', summary: { wirelessRate: 33.9, wiredRate: 22, retailArpuRate: 96, usimMnpRate: 31, totalAmount: 0, wirelessDetails: {target: 620, current: 210}, wiredDetails: {target: 90, current: 20}, retailDetails: {target: 80186, current: 77000}, mnpDetails: {target: 45, current: 15}, benefitHighUpgrade: 12, benefitHighMnp: 3, benefitGal26: 2 }, targetStatus: { goalScore: 90, currentScore: 33.9, bonusUsageRate: 70, aiSuggestion: "개선 유도 필요" }, strengths: [{ name: "5G 전체", score: 105 }, { name: "LTE 신규", score: 8 }], detailedItems: [{ name: "LTE 신규", multiplier: 1.0, performance: 8, score: 8 }, { name: "5G 전체", multiplier: 1.0, performance: 105, score: 105 }] },
                { id: 'D33586', name: '동이', manager: '김기획', summary: { wirelessRate: 45.2, wiredRate: 45, retailArpuRate: 100, usimMnpRate: 42, totalAmount: 8800000, wirelessDetails: {target: 210, current: 95}, wiredDetails: {target: 100, current: 45}, retailDetails: {target: 80186, current: 80500}, mnpDetails: {target: 60, current: 28}, benefitHighUpgrade: 55, benefitHighMnp: 9, benefitGal26: 6 }, targetStatus: { goalScore: 90, currentScore: 45.2, bonusUsageRate: 92, aiSuggestion: "최우수 실적군" }, strengths: [{ name: "5G 전체", score: 85 }, { name: "전연령 010신규", score: 15 }], detailedItems: [{ name: "LTE 신규", multiplier: 1.0, performance: 10, score: 10 }, { name: "5G 전체", multiplier: 1.0, performance: 85, score: 85 }] },
                { id: 'D33724', name: '가람', manager: '김기획', summary: { wirelessRate: 34.9, wiredRate: 38, retailArpuRate: 99, usimMnpRate: 33, totalAmount: 3200000, wirelessDetails: {target: 430, current: 150}, wiredDetails: {target: 170, current: 65}, retailDetails: {target: 80186, current: 79500}, mnpDetails: {target: 90, current: 22}, benefitHighUpgrade: 33, benefitHighMnp: 6, benefitGal26: 4 }, targetStatus: { goalScore: 90, currentScore: 34.9, bonusUsageRate: 75, aiSuggestion: "안정성 확보" }, strengths: [{ name: "5G 전체", score: 110 }, { name: "LTE 신규", score: 12 }], detailedItems: [{ name: "LTE 신규", multiplier: 1.0, performance: 12, score: 12 }, { name: "5G 전체", multiplier: 1.0, performance: 110, score: 110 }] },
                { id: 'D33648', name: 'SK매우만족', manager: '김기획', summary: { wirelessRate: 41.2, wiredRate: 44, retailArpuRate: 101, usimMnpRate: 40, totalAmount: 10500000, wirelessDetails: {target: 510, current: 210}, wiredDetails: {target: 200, current: 88}, retailDetails: {target: 80186, current: 81200}, mnpDetails: {target: 110, current: 35}, benefitHighUpgrade: 68, benefitHighMnp: 15, benefitGal26: 10 }, targetStatus: { goalScore: 90, currentScore: 41.2, bonusUsageRate: 85, aiSuggestion: "높은 고객 만족도" }, strengths: [{ name: "5G 전체", score: 130 }, { name: "전연령 010신규", score: 18 }], detailedItems: [{ name: "LTE 신규", multiplier: 1.0, performance: 15, score: 15 }, { name: "5G 전체", multiplier: 1.0, performance: 130, score: 130 }] },
                { id: 'D33377', name: '왜관', manager: '김기획', summary: { wirelessRate: 28.9, wiredRate: 26, retailArpuRate: 94, usimMnpRate: 25, totalAmount: 0, wirelessDetails: {target: 380, current: 110}, wiredDetails: {target: 130, current: 35}, retailDetails: {target: 80186, current: 76000}, mnpDetails: {target: 70, current: 10}, benefitHighUpgrade: 20, benefitHighMnp: 4, benefitGal26: 2 }, targetStatus: { goalScore: 90, currentScore: 28.9, bonusUsageRate: 60, aiSuggestion: "대책 수립 요망" }, strengths: [{ name: "5G 전체", score: 90 }, { name: "LTE 신규", score: 5 }], detailedItems: [{ name: "LTE 신규", multiplier: 1.0, performance: 5, score: 5 }, { name: "5G 전체", multiplier: 1.0, performance: 90, score: 90 }] },
                { id: 'D33159', name: '안동남부', manager: '이마케', summary: { wirelessRate: 35.6, wiredRate: 37, retailArpuRate: 99, usimMnpRate: 36, totalAmount: 4100000, wirelessDetails: {target: 450, current: 160}, wiredDetails: {target: 160, current: 60}, retailDetails: {target: 80186, current: 79800}, mnpDetails: {target: 85, current: 24}, benefitHighUpgrade: 25, benefitHighMnp: 5, benefitGal26: 3 }, targetStatus: { goalScore: 90, currentScore: 35.6, bonusUsageRate: 78, aiSuggestion: "남부 지역 거점" }, strengths: [{ name: "5G 전체", score: 115 }, { name: "전연령 010신규", score: 12 }], detailedItems: [{ name: "LTE 신규", multiplier: 1.0, performance: 12, score: 12 }, { name: "5G 전체", multiplier: 1.0, performance: 115, score: 115 }] },
                { id: 'D33655', name: '안동삼성', manager: '이마케', summary: { wirelessRate: 39.1, wiredRate: 40, retailArpuRate: 100, usimMnpRate: 41, totalAmount: 7500000, wirelessDetails: {target: 320, current: 125}, wiredDetails: {target: 110, current: 45}, retailDetails: {target: 80186, current: 80500}, mnpDetails: {target: 65, current: 27}, benefitHighUpgrade: 40, benefitHighMnp: 8, benefitGal26: 5 }, targetStatus: { goalScore: 90, currentScore: 39.1, bonusUsageRate: 83, aiSuggestion: "삼성 브랜드 시너지" }, strengths: [{ name: "5G 전체", score: 100 }, { name: "전연령 010신규", score: 22 }], detailedItems: [{ name: "LTE 신규", multiplier: 1.0, performance: 18, score: 18 }, { name: "5G 전체", multiplier: 1.0, performance: 100, score: 100 }] },
                { id: 'D33734', name: '봉화', manager: '이마케', summary: { wirelessRate: 32.1, wiredRate: 27, retailArpuRate: 97, usimMnpRate: 30, totalAmount: 0, wirelessDetails: {target: 280, current: 90}, wiredDetails: {target: 90, current: 25}, retailDetails: {target: 80186, current: 78000}, mnpDetails: {target: 55, current: 14}, benefitHighUpgrade: 15, benefitHighMnp: 2, benefitGal26: 1 }, targetStatus: { goalScore: 90, currentScore: 32.1, bonusUsageRate: 68, aiSuggestion: "봉화 지역 확대 지시" }, strengths: [{ name: "5G 전체", score: 80 }, { name: "LTE 신규", score: 7 }], detailedItems: [{ name: "LTE 신규", multiplier: 1.0, performance: 7, score: 7 }, { name: "5G 전체", multiplier: 1.0, performance: 80, score: 80 }] },
                { id: 'D33729', name: '드림라인', manager: '이마케', summary: { wirelessRate: 35.7, wiredRate: 39, retailArpuRate: 99, usimMnpRate: 37, totalAmount: 5200000, wirelessDetails: {target: 490, current: 175}, wiredDetails: {target: 190, current: 75}, retailDetails: {target: 80186, current: 80000}, mnpDetails: {target: 95, current: 26}, benefitHighUpgrade: 33, benefitHighMnp: 6, benefitGal26: 4 }, targetStatus: { goalScore: 90, currentScore: 35.7, bonusUsageRate: 80, aiSuggestion: "목표치 상향 검토" }, strengths: [{ name: "5G 전체", score: 125 }, { name: "전연령 010신규", score: 14 }], detailedItems: [{ name: "LTE 신규", multiplier: 1.0, performance: 13, score: 13 }, { name: "5G 전체", multiplier: 1.0, performance: 125, score: 125 }] },
                { id: 'D33198', name: '영주제일', manager: '이마케', summary: { wirelessRate: 40.0, wiredRate: 45, retailArpuRate: 101, usimMnpRate: 43, totalAmount: 11800000, wirelessDetails: {target: 550, current: 220}, wiredDetails: {target: 210, current: 95}, retailDetails: {target: 80186, current: 81500}, mnpDetails: {target: 105, current: 32}, benefitHighUpgrade: 72, benefitHighMnp: 18, benefitGal26: 12 }, targetStatus: { goalScore: 90, currentScore: 40.0, bonusUsageRate: 86, aiSuggestion: "영주 1위 대리점" }, strengths: [{ name: "5G 전체", score: 150 }, { name: "전연령 010신규", score: 19 }], detailedItems: [{ name: "LTE 신규", multiplier: 1.0, performance: 16, score: 16 }, { name: "5G 전체", multiplier: 1.0, performance: 150, score: 150 }] },
                { id: 'D33662', name: '티엔에스', manager: '이마케', summary: { wirelessRate: 33.9, wiredRate: 33, retailArpuRate: 97, usimMnpRate: 34, totalAmount: 0, wirelessDetails: {target: 310, current: 105}, wiredDetails: {target: 120, current: 40}, retailDetails: {target: 80186, current: 78500}, mnpDetails: {target: 60, current: 18}, benefitHighUpgrade: 20, benefitHighMnp: 5, benefitGal26: 3 }, targetStatus: { goalScore: 90, currentScore: 33.9, bonusUsageRate: 72, aiSuggestion: "부진 사유 분석" }, strengths: [{ name: "5G 전체", score: 95 }, { name: "LTE 신규", score: 8 }], detailedItems: [{ name: "LTE 신규", multiplier: 1.0, performance: 8, score: 8 }, { name: "5G 전체", multiplier: 1.0, performance: 95, score: 95 }] },
                { id: 'D33435', name: '스피드', manager: '이마케', summary: { wirelessRate: 38.3, wiredRate: 38, retailArpuRate: 100, usimMnpRate: 39, totalAmount: 9500000, wirelessDetails: {target: 470, current: 180}, wiredDetails: {target: 180, current: 70}, retailDetails: {target: 80186, current: 80200}, mnpDetails: {target: 85, current: 25}, benefitHighUpgrade: 48, benefitHighMnp: 10, benefitGal26: 7 }, targetStatus: { goalScore: 90, currentScore: 38.3, bonusUsageRate: 81, aiSuggestion: "속도감 있는 영업" }, strengths: [{ name: "5G 전체", score: 120 }, { name: "LTE 신규", score: 14 }], detailedItems: [{ name: "LTE 신규", multiplier: 1.0, performance: 14, score: 14 }, { name: "5G 전체", multiplier: 1.0, performance: 120, score: 120 }] },
                { id: 'D33610', name: '친절', manager: '이마케', summary: { wirelessRate: 37.2, wiredRate: 39, retailArpuRate: 98, usimMnpRate: 36, totalAmount: 3800000, wirelessDetails: {target: 390, current: 145}, wiredDetails: {target: 140, current: 55}, retailDetails: {target: 80186, current: 79000}, mnpDetails: {target: 75, current: 21}, benefitHighUpgrade: 22, benefitHighMnp: 4, benefitGal26: 2 }, targetStatus: { goalScore: 90, currentScore: 37.2, bonusUsageRate: 76, aiSuggestion: "친절 마케팅 강화" }, strengths: [{ name: "5G 전체", score: 105 }, { name: "LTE 신규", score: 11 }], detailedItems: [{ name: "LTE 신규", multiplier: 1.0, performance: 11, score: 11 }, { name: "5G 전체", multiplier: 1.0, performance: 105, score: 105 }] },
                { id: 'D33115', name: '안동', manager: '이마케', summary: { wirelessRate: 35.8, wiredRate: 39, retailArpuRate: 100, usimMnpRate: 40, totalAmount: 13500000, wirelessDetails: {target: 600, current: 215}, wiredDetails: {target: 230, current: 90}, retailDetails: {target: 80186, current: 80800}, mnpDetails: {target: 115, current: 31}, benefitHighUpgrade: 82, benefitHighMnp: 20, benefitGal26: 15 }, targetStatus: { goalScore: 90, currentScore: 35.8, bonusUsageRate: 84, aiSuggestion: "안동 권역 주도" }, strengths: [{ name: "5G 전체", score: 140 }, { name: "전연령 010신규", score: 20 }], detailedItems: [{ name: "LTE 신규", multiplier: 1.0, performance: 17, score: 17 }, { name: "5G 전체", multiplier: 1.0, performance: 140, score: 140 }] },
                { id: 'D33675', name: 'SK역전', manager: '이마케', summary: { wirelessRate: 33.8, wiredRate: 34, retailArpuRate: 97, usimMnpRate: 32, totalAmount: 0, wirelessDetails: {target: 340, current: 115}, wiredDetails: {target: 130, current: 45}, retailDetails: {target: 80186, current: 78200}, mnpDetails: {target: 65, current: 17}, benefitHighUpgrade: 10, benefitHighMnp: 2, benefitGal26: 1 }, targetStatus: { goalScore: 90, currentScore: 33.8, bonusUsageRate: 71, aiSuggestion: "역전 만회 전략" }, strengths: [{ name: "5G 전체", score: 90 }, { name: "LTE 신규", score: 9 }], detailedItems: [{ name: "LTE 신규", multiplier: 1.0, performance: 9, score: 9 }, { name: "5G 전체", multiplier: 1.0, performance: 90, score: 90 }] },
                { id: 'D33697', name: '영풍', manager: '박영업', summary: { wirelessRate: 38.0, wiredRate: 40, retailArpuRate: 100, usimMnpRate: 38, totalAmount: 8200000, wirelessDetails: {target: 460, current: 175}, wiredDetails: {target: 160, current: 65}, retailDetails: {target: 80186, current: 80300}, mnpDetails: {target: 80, current: 24}, benefitHighUpgrade: 50, benefitHighMnp: 10, benefitGal26: 7 }, targetStatus: { goalScore: 90, currentScore: 38.0, bonusUsageRate: 80, aiSuggestion: "포항/영덕 인접 영업" }, strengths: [{ name: "5G 전체", score: 110 }, { name: "전연령 010신규", score: 16 }], detailedItems: [{ name: "LTE 신규", multiplier: 1.0, performance: 13, score: 13 }, { name: "5G 전체", multiplier: 1.0, performance: 110, score: 110 }] },
                { id: 'D33676', name: '상주중앙', manager: '박영업', summary: { wirelessRate: 34.5, wiredRate: 35, retailArpuRate: 98, usimMnpRate: 34, totalAmount: 2900000, wirelessDetails: {target: 290, current: 100}, wiredDetails: {target: 100, current: 35}, retailDetails: {target: 80186, current: 78800}, mnpDetails: {target: 50, current: 15}, benefitHighUpgrade: 18, benefitHighMnp: 4, benefitGal26: 2 }, targetStatus: { goalScore: 90, currentScore: 34.5, bonusUsageRate: 74, aiSuggestion: "중앙 핵심 상권" }, strengths: [{ name: "5G 전체", score: 85 }, { name: "LTE 신규", score: 10 }], detailedItems: [{ name: "LTE 신규", multiplier: 1.0, performance: 10, score: 10 }, { name: "5G 전체", multiplier: 1.0, performance: 85, score: 85 }] },
                { id: 'D33468', name: '용상', manager: '박영업', summary: { wirelessRate: 38.7, wiredRate: 42, retailArpuRate: 101, usimMnpRate: 41, totalAmount: 11500000, wirelessDetails: {target: 530, current: 205}, wiredDetails: {target: 200, current: 85}, retailDetails: {target: 80186, current: 81100}, mnpDetails: {target: 95, current: 30}, benefitHighUpgrade: 65, benefitHighMnp: 14, benefitGal26: 10 }, targetStatus: { goalScore: 90, currentScore: 38.7, bonusUsageRate: 85, aiSuggestion: "안동 용상 핵심" }, strengths: [{ name: "5G 전체", score: 135 }, { name: "전연령 010신규", score: 18 }], detailedItems: [{ name: "LTE 신규", multiplier: 1.0, performance: 15, score: 15 }, { name: "5G 전체", multiplier: 1.0, performance: 135, score: 135 }] },
                { id: 'D33301', name: '구미동남', manager: '박영업', summary: { wirelessRate: 36.9, wiredRate: 40, retailArpuRate: 100, usimMnpRate: 40, totalAmount: 16000000, wirelessDetails: {target: 650, current: 240}, wiredDetails: {target: 250, current: 100}, retailDetails: {target: 80186, current: 80900}, mnpDetails: {target: 120, current: 34}, benefitHighUpgrade: 95, benefitHighMnp: 22, benefitGal26: 18 }, targetStatus: { goalScore: 90, currentScore: 36.9, bonusUsageRate: 83, aiSuggestion: "구미 최대 실적" }, strengths: [{ name: "5G 전체", score: 160 }, { name: "전연령 010신규", score: 25 }], detailedItems: [{ name: "LTE 신규", multiplier: 1.0, performance: 20, score: 20 }, { name: "5G 전체", multiplier: 1.0, performance: 160, score: 160 }] },
                { id: 'D33551', name: '나비', manager: '박영업', summary: { wirelessRate: 33.8, wiredRate: 32, retailArpuRate: 96, usimMnpRate: 30, totalAmount: 0, wirelessDetails: {target: 370, current: 125}, wiredDetails: {target: 140, current: 45}, retailDetails: {target: 80186, current: 77500}, mnpDetails: {target: 65, current: 16}, benefitHighUpgrade: 15, benefitHighMnp: 3, benefitGal26: 2 }, targetStatus: { goalScore: 90, currentScore: 33.8, bonusUsageRate: 69, aiSuggestion: "나비 효과 기대" }, strengths: [{ name: "5G 전체", score: 100 }, { name: "LTE 신규", score: 8 }], detailedItems: [{ name: "LTE 신규", multiplier: 1.0, performance: 8, score: 8 }, { name: "5G 전체", multiplier: 1.0, performance: 100, score: 100 }] },
                { id: 'D33723', name: '고객사랑', manager: '박영업', summary: { wirelessRate: 39.6, wiredRate: 44, retailArpuRate: 101, usimMnpRate: 44, totalAmount: 12500000, wirelessDetails: {target: 480, current: 190}, wiredDetails: {target: 170, current: 75}, retailDetails: {target: 80186, current: 81400}, mnpDetails: {target: 85, current: 31}, benefitHighUpgrade: 75, benefitHighMnp: 16, benefitGal26: 11 }, targetStatus: { goalScore: 90, currentScore: 39.6, bonusUsageRate: 88, aiSuggestion: "친절 마케팅의 정석" }, strengths: [{ name: "5G 전체", score: 120 }, { name: "전연령 010신규", score: 22 }], detailedItems: [{ name: "LTE 신규", multiplier: 1.0, performance: 18, score: 18 }, { name: "5G 전체", multiplier: 1.0, performance: 120, score: 120 }] },
                { id: 'D33512', name: 'SK군위', manager: '박영업', summary: { wirelessRate: 36.5, wiredRate: 38, retailArpuRate: 98, usimMnpRate: 35, totalAmount: 3600000, wirelessDetails: {target: 260, current: 95}, wiredDetails: {target: 90, current: 35}, retailDetails: {target: 80186, current: 79200}, mnpDetails: {target: 45, current: 14}, benefitHighUpgrade: 20, benefitHighMnp: 5, benefitGal26: 3 }, targetStatus: { goalScore: 90, currentScore: 36.5, bonusUsageRate: 77, aiSuggestion: "군위 상권 독점" }, strengths: [{ name: "5G 전체", score: 80 }, { name: "LTE 신규", score: 10 }], detailedItems: [{ name: "LTE 신규", multiplier: 1.0, performance: 10, score: 10 }, { name: "5G 전체", multiplier: 1.0, performance: 80, score: 80 }] },
                { id: 'D33113', name: '상주', manager: '박영업', summary: { wirelessRate: 34.8, wiredRate: 36, retailArpuRate: 99, usimMnpRate: 37, totalAmount: 5800000, wirelessDetails: {target: 560, current: 195}, wiredDetails: {target: 220, current: 80}, retailDetails: {target: 80186, current: 80100}, mnpDetails: {target: 100, current: 27}, benefitHighUpgrade: 42, benefitHighMnp: 9, benefitGal26: 6 }, targetStatus: { goalScore: 90, currentScore: 34.8, bonusUsageRate: 79, aiSuggestion: "상주 대표 대리점" }, strengths: [{ name: "5G 전체", score: 130 }, { name: "전연령 010신규", score: 15 }], detailedItems: [{ name: "LTE 신규", multiplier: 1.0, performance: 12, score: 12 }, { name: "5G 전체", multiplier: 1.0, performance: 130, score: 130 }] },
                { id: 'D33591', name: '문경하늘', manager: '박영업', summary: { wirelessRate: 33.9, wiredRate: 35, retailArpuRate: 97, usimMnpRate: 32, totalAmount: 0, wirelessDetails: {target: 330, current: 112}, wiredDetails: {target: 120, current: 42}, retailDetails: {target: 80186, current: 78400}, mnpDetails: {target: 55, current: 16}, benefitHighUpgrade: 18, benefitHighMnp: 4, benefitGal26: 2 }, targetStatus: { goalScore: 90, currentScore: 33.9, bonusUsageRate: 73, aiSuggestion: "하늘 높이 비상 필요" }, strengths: [{ name: "5G 전체", score: 95 }, { name: "LTE 신규", score: 9 }], detailedItems: [{ name: "LTE 신규", multiplier: 1.0, performance: 9, score: 9 }, { name: "5G 전체", multiplier: 1.0, performance: 95, score: 95 }] }
            ],
            allAgencies: []
        },
        3: { global: { baseDate: '2026-03-31', totalBusinessDays: 22, currentBusinessDay: 22, wirelessDays: 27, wiredDays: 23.1, elapsedDays: 27, wirelessProgress: 1.0, wiredProgress: 1.0, prevMonth: { achievedCount: 19, totalAmount: 140000000 } }, agencies: [], allAgencies: [] },
        2: { global: { baseDate: '2026-02-28', totalBusinessDays: 20, currentBusinessDay: 20, wirelessDays: 25, wiredDays: 21, elapsedDays: 25, wirelessProgress: 1.0, wiredProgress: 1.0, prevMonth: { achievedCount: 18, totalAmount: 160000000 } }, agencies: [], allAgencies: [] },
        1: { global: { baseDate: '2026-01-31', totalBusinessDays: 22, currentBusinessDay: 22, wirelessDays: 27, wiredDays: 23, elapsedDays: 27, wirelessProgress: 1.0, wiredProgress: 1.0, prevMonth: { achievedCount: 15, totalAmount: 140000000 } }, agencies: [], allAgencies: [] }
    }
};

// --- Helper: Generate Dummy Stores for an Agency ---
function generateDummyStores(agencyName, totalAmount) {
    return [
        { 
            name: `${agencyName} 1호점`, 
            wirelessPoint: Math.round(100 + Math.random() * 50), 
            wirelessPaymentTable: totalAmount > 5000000 ? "1그룹" : "2그룹", 
            wiredPoint: Math.round(50 + Math.random() * 40), 
            wiredPaymentTable: "2그룹", 
            finalPayment: Math.round(totalAmount * 0.65), 
            progressRate: Math.round(90 + Math.random() * 60), 
            diffFrom3Months: Math.round((Math.random() - 0.3) * 20) 
        },
        { 
            name: `${agencyName} 2호점`, 
            wirelessPoint: Math.round(80 + Math.random() * 40), 
            wirelessPaymentTable: "2그룹", 
            wiredPoint: Math.round(30 + Math.random() * 30), 
            wiredPaymentTable: "3그룹", 
            finalPayment: Math.round(totalAmount * 0.35), 
            progressRate: Math.round(80 + Math.random() * 50), 
            diffFrom3Months: Math.round((Math.random() - 0.5) * 15) 
        }
    ];
}

// --- Initialize Month 4 Stores ---
dashboardData.months[4].agencies.forEach(ag => {
    ag.stores = generateDummyStores(ag.name, ag.summary.totalAmount);
});

// --- Dummy Data Generator for Historical Months (1-3) ---
[1, 2, 3].forEach(m => {
    const scale = 0.6 + (m * 0.1); 
    dashboardData.months[m].agencies = dashboardData.months[4].agencies.map(ag => {
        const newAg = JSON.parse(JSON.stringify(ag));
        newAg.summary.totalAmount = Math.round(ag.summary.totalAmount * scale);
        newAg.summary.totalAmount += (Math.random() - 0.5) * 1000000;
        if (newAg.summary.totalAmount < 0) newAg.summary.totalAmount = 0;
        
        // Regenerate stores with scaled amount for history
        newAg.stores = generateDummyStores(ag.name, newAg.summary.totalAmount);
        
        return newAg;
    });
});

// --- Mapping Logic (Populate allAgencies for all months) ---
Object.keys(dashboardData.months).forEach(m => {
    const month = dashboardData.months[m];
    month.agencies.forEach(ag => {
        month.allAgencies.push({
            "대리점명": ag.name, 
            "팀명": "경북", 
            "담당자": ag.manager,
            "코드": ag.id,
            "무선목표": ag.summary.wirelessDetails.target, 
            "무선실적": ag.summary.wirelessDetails.current, 
            "무선달성률": ag.summary.wirelessRate / 100,
            "유선목표": ag.summary.wiredDetails.target, 
            "유선실적": ag.summary.wiredDetails.current, 
            "유선달성률": ag.summary.wiredRate / 100,
            "소매ARPU목표": ag.summary.retailDetails ? ag.summary.retailDetails.target : 80186, 
            "소매ARPU실적": ag.summary.retailDetails ? ag.summary.retailDetails.current : 80186, 
            "소매ARPU달성률": ag.summary.retailArpuRate / 100,
            "ARPU달성그룹": ag.summary.retailArpuRate >= 100 ? "1" : "2",
            "유심목표": ag.summary.mnpDetails ? ag.summary.mnpDetails.target : 50, 
            "유심달성률": ag.summary.usimMnpRate / 100, 
            "유심실적가점": ag.summary.mnpDetails ? ag.summary.mnpDetails.current : 0,
            "초고속달성률": (ag.summary.wiredRate / 100) * 0.95, // Dummy calculation
            "공통지원금등록률": ag.targetStatus.bonusUsageRate / 100, 
            "달성여부": ag.summary.totalAmount > 0 ? "달성" : "미달성",
            "최종지급테이블": ag.summary.totalAmount > 10000000 ? "1그룹" : (ag.summary.totalAmount > 0 ? "2그룹" : "3그룹"),
            "수혜금액": ag.summary.totalAmount, 
            "TACplus": 1,
            "고가기변": ag.summary.benefitHighUpgrade || Math.round(Math.random() * 50),
            "고가MNP": ag.summary.benefitHighMnp || Math.round(Math.random() * 20),
            "유심중고": ag.summary.benefitGal26 || Math.round(Math.random() * 10)
        });
    });
});

if (typeof module !== 'undefined') module.exports = dashboardData;
